# Generated by Django 4.1 on 2022-10-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_location_loc_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="loc_short_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="location",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
