# Generated by Django 4.1 on 2022-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_location_created_by_alter_location_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_by',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
