# Generated by Django 4.1 on 2022-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_location_created_by_alter_location_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routedetail',
            name='arrive_in_min',
            field=models.IntegerField(default=0),
        ),
    ]
