# Generated by Django 4.1 on 2022-10-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_routedetail_arrive_in_min'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routedetail',
            unique_together={('route', 'location')},
        ),
    ]
